name: Scraper Quotidien

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch: 

jobs:
  execution-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les librairies (Supabase et Playwright)
        run: |
          pip install -r requirements.txt
          pip install playwright playwright-stealth

      - name: Installer le navigateur Chromium
        run: playwright install chromium

      - name: Lancer la recherche immobilière !
        run: python scraper.py
